Cloud/Cloud/Controllers/OrderdetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cloud.Models;

namespace Cloud.Controllers
{
    public class OrderdetailsController : Controller
    {
        private readonly Group08ElectricmtContext _context;

        public OrderdetailsController(Group08ElectricmtContext context)
        {
            _context = context;
        }

        // GET: Orderdetails
        public async Task<IActionResult> Index()
        {
              return _context.TblOrderdetails != null ? 
                          View(await _context.TblOrderdetails.ToListAsync()) :
                          Problem("Entity set 'Group08ElectricmtContext.TblOrderdetails'  is null.");
        }

        // GET: Orderdetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TblOrderdetails == null)
            {
                return NotFound();
            }

            var tblOrderdetail = await _context.TblOrderdetails
                .FirstOrDefaultAsync(m => m.EntryId == id);
            if (tblOrderdetail == null)
            {
                return NotFound();
            }

            return View(tblOrderdetail);
        }

        // GET: Orderdetails/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Orderdetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TblOrderdetail neworder)
        {
            if (ModelState.IsValid)
            {
                if (HttpContext.Session.GetInt32("orderID") != null)
                {
                    int ordnum = (from ord in _context.TblOrderdetails
                                  select ord).Count();

                    neworder.EntryId = ordnum + 1;
                    neworder.Status = 1;
                    neworder.OrderId = HttpContext.Session.GetInt32("orderID");
                    neworder.CompId = HttpContext.Session.GetInt32("companyID");

                    _context.Add(neworder); // Orderdetail
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction("Create", "Orders");
                }
            }
            return View(neworder);
        }

        // GET: Orderdetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TblOrderdetails == null)
            {
                return NotFound();
            }

            var tblOrderdetail = await _context.TblOrderdetails.FindAsync(id);
            if (tblOrderdetail == null)
            {
                return NotFound();
            }
            return View(tblOrderdetail);
        }

        // POST: Orderdetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EntryId,OrderId,ItemId,ItemQuantity,CompId,Status")] TblOrderdetail tblOrderdetail)
        {
            if (id != tblOrderdetail.EntryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblOrderdetail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblOrderdetailExists(tblOrderdetail.EntryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tblOrderdetail);
        }

        // GET: Orderdetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TblOrderdetails == null)
            {
                return NotFound();
            }

            var tblOrderdetail = await _context.TblOrderdetails
                .FirstOrDefaultAsync(m => m.EntryId == id);
            if (tblOrderdetail == null)
            {
                return NotFound();
            }

            return View(tblOrderdetail);
        }

        // POST: Orderdetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TblOrderdetails == null)
            {
                return Problem("Entity set 'Group08ElectricmtContext.TblOrderdetails'  is null.");
            }
            var tblOrderdetail = await _context.TblOrderdetails.FindAsync(id);
            if (tblOrderdetail != null)
            {
                _context.TblOrderdetails.Remove(tblOrderdetail);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblOrderdetailExists(int id)
        {
          return (_context.TblOrderdetails?.Any(e => e.EntryId == id)).GetValueOrDefault();
        }
    }
}

Cloud/Cloud/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cloud.Models;

namespace Cloud.Controllers
{
    public class OrdersController : Controller
    {
        private readonly Group08ElectricmtContext _context;

        public OrdersController(Group08ElectricmtContext context)
        {
            _context = context;
        }

        // GET: Orders
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("email") == null)
            {
                return RedirectToAction("Login", "Company");
            }
            else
            {

                int companyID = Convert.ToInt32(HttpContext.Session.GetInt32("companyID"));

                List<TblOrder> listOrd = _context.TblOrders.Where(emp => emp.Status == 1 && emp.CompId == companyID).Select(emp => emp).ToList();

                return View(listOrd);
            }
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TblOrders == null)
            {
                return NotFound();
            }

            var tblOrder = await _context.TblOrders
                .FirstOrDefaultAsync(m => m.ReportId == id);
            if (tblOrder == null)
            {
                return NotFound();
            }

            return View(tblOrder);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TblOrder neworder)
        {
            if (ModelState.IsValid)
            {
                int ordnum = (from ord in _context.TblOrders
                              select ord).Count();

                neworder.ReportId = ordnum + 1;
                neworder.CompId = HttpContext.Session.GetInt32("companyID");
                neworder.OrderDelivered = 1;
                neworder.OrderDate = DateTime.Now;
                neworder.Status = 1;

                _context.Add(neworder);
                _context.SaveChangesAsync();

                int ordnumnew = (from ord in _context.TblOrders
                                 select ord).Count();

                if ((ordnumnew = ordnum) != 1)
                {
                    HttpContext.Session.SetInt32("orderID", ordnum);
                }
                else return RedirectToAction(nameof(Index));
            }

            return View(neworder);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TblOrders == null)
            {
                return NotFound();
            }

            var tblOrder = await _context.TblOrders
                .FirstOrDefaultAsync(m => m.ReportId == id);
            if (tblOrder == null)
            {
                return NotFound();
            }

            return View(tblOrder);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TblOrders == null)
            {
                return Problem("Entity set 'Group08ElectricmtContext.TblOrders'  is null.");
            }
            var tblOrder = await _context.TblOrders.FindAsync(id);
            if (tblOrder != null)
            {
                _context.TblOrders.Remove(tblOrder);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblOrderExists(int id)
        {
          return (_context.TblOrders?.Any(e => e.ReportId == id)).GetValueOrDefault();
        }
    }
}

Cloud/Cloud/Views/Orders/Create.cshtml
@model Cloud.Models.TblOrder

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>TblOrder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="submit" value="Create a new order" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Cloud/Cloud/Views/Orders/Delete.cshtml
@model Cloud.Models.TblOrder

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TblOrder</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDelivered)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDelivered)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ReportId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Cloud/Cloud/Views/Orders/Details.cshtml
@model Cloud.Models.TblOrder

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Orders</h1>

<div>

    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDelivered)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDelivered)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ReportId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Cloud/Cloud/Views/Orders/Index.cshtml
@model IEnumerable<Cloud.Models.TblOrder>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Manage your orders</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Company ID
            </th>
            <th>
                Delivered
            </th>
            <th>
                Place date
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CompId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDelivered)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDate)
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@item.ReportId">Delete</a>
            </td>
        </tr>
}

    
    </tbody>

</table>

<a asp-action="Create" asp-controller="Orderdetails">To order details</a>