Cloud/Cloud/Controllers/EmployeeController.cs
using AutoMapper;
using Cloud.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.Design;
using System.Security.Cryptography;
using System.Text;

namespace Cloud.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly Group08ElectricmtContext context;

        public EmployeeController(Group08ElectricmtContext context)
        {
            this.context = context;
        }

        public static string HashPassword(string input)
        {
            using (SHA256 sha256 = SHA256.Create())
            {
                // Convert the input string to a byte array and compute the hash
                byte[] inputBytes = Encoding.UTF8.GetBytes(input);
                byte[] hashBytes = sha256.ComputeHash(inputBytes);

                // Convert the byte array to a hexadecimal string
                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < hashBytes.Length; i++)
                {
                    sb.Append(hashBytes[i].ToString("x2"));
                }
                return sb.ToString();
            }
        }

        public IActionResult Index()
        {
            if(HttpContext.Session.GetString("email") == null)
            {
                return RedirectToAction("Login", "Company");
            }
            else
            { 

                int companyID = Convert.ToInt32(HttpContext.Session.GetInt32("companyID"));

                List<TblEmployee> listEmp = context.TblEmployees.Where(emp => emp.Status == 1 && emp.CompId == companyID).Select(emp => emp).ToList();

                return View(listEmp);
            }
        }

        public IActionResult Edit(int id)
        {
            TblEmployee target = (from emp in context.TblEmployees
                                  where emp.EmplId == id &&
                                  emp.Status == 1
                                  select emp).SingleOrDefault();

            var maxCompId = context.TblCompanies.Max(c => c.CompId);
            var minCompId = context.TblCompanies.Min(c => c.CompId);

            ViewBag.MaxCompId = maxCompId;
            ViewBag.MinCompId = minCompId;


            return View(target);
        }

        [HttpPost]
        public IActionResult Edit(TblEmployee employee)
        {
            var existingEmployee = context.TblEmployees.FirstOrDefault(e => e.EmplId == employee.EmplId);

            if (existingEmployee == null)
            {
                return NotFound();
            }

            existingEmployee.EmplFirstname = employee.EmplFirstname;
            existingEmployee.EmplLastname = employee.EmplLastname;
            existingEmployee.CompId = employee.CompId;
            existingEmployee.EmplEmail = employee.EmplEmail;

            context.TblEmployees.Update(existingEmployee);
            context.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult Details(int id)
        {
            TblEmployee employee = (from emp in context.TblEmployees
                                    where emp.EmplId == id
                                    && emp.Status == 1
                                    select emp).SingleOrDefault();

            TblTruck truck = context.TblTrucks.Where(t => t.EmplId == id).SingleOrDefault();
            List<TruckItemView> ListItem = new List<TruckItemView>();

            int companyID = Convert.ToInt32(HttpContext.Session.GetInt32("companyID"));
            var result = (from i in context.TblItems
                          join t in context.TblTruckItems
            on i.ItemId equals t.ItemId
                          where i.CompId == companyID && t.TruckId == truck.TruckId
                          select new
                          {
                              Item_Name = i.ItemName,
                              Item_Quantity = t.ItemQuantity
                          });

            foreach (var item in result)
            {
                TruckItemView truckitemview = new TruckItemView(item.Item_Name, item.Item_Quantity ?? 0);
                ListItem.Add(truckitemview);
            }


            EmployeeTruckItem v = new EmployeeTruckItem(employee, truck, ListItem);
            return View(v);
        }

        public IActionResult Delete(int id)
        {
            TblEmployee employee = (from emp in context.TblEmployees
                                    where emp.EmplId == id
                                    && emp.Status == 1
                                    select emp).SingleOrDefault();
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }
        [HttpPost]
        public IActionResult Delete(TblEmployee employee)
        {
            var v = context.TblEmployees.FirstOrDefault(e => e.EmplId == employee.EmplId);

            if (employee == null)
            {
                return NotFound();
            }

            v.Status = 0;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TblEmployee newemp)
        {
            if (ModelState.IsValid)
            {
                int empnum = (from emp in context.TblEmployees
                               select emp).Count();

                newemp.EmplId = empnum + 1;
                newemp.Status = 1;
                newemp.EmplPassword = HashPassword("password");
                newemp.CompId = HttpContext.Session.GetInt32("companyID");

                context.Add(newemp);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(newemp);
        }
    }
}

Cloud/Cloud/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cloud.Models;

namespace Cloud.Controllers
{
    public class OrdersController : Controller
    {
        private readonly Group08ElectricmtContext _context;

        public OrdersController(Group08ElectricmtContext context)
        {
            _context = context;
        }

        // GET: Orders
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("email") == null)
            {
                return RedirectToAction("Login", "Company");
            }
            else
            {

                int companyID = Convert.ToInt32(HttpContext.Session.GetInt32("companyID"));

                List<TblOrder> listOrd = _context.TblOrders.Where(emp => emp.Status == 1 && emp.CompId == companyID).Select(emp => emp).ToList();

                return View(listOrd);
            }
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TblOrders == null)
            {
                return NotFound();
            }

            var tblOrder = await _context.TblOrders
                .FirstOrDefaultAsync(m => m.ReportId == id);
            if (tblOrder == null)
            {
                return NotFound();
            }

            return View(tblOrder);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TblOrder neworder)
        {
            if (ModelState.IsValid)
            {
                int ordnum = (from ord in _context.TblOrders
                              select ord).Count();

                neworder.ReportId = ordnum + 1;
                neworder.CompId = HttpContext.Session.GetInt32("companyID");
                neworder.OrderDelivered = 1;
                neworder.OrderDate = DateTime.Now;
                neworder.Status = 1;

                _context.Add(neworder);
                _context.SaveChangesAsync();

                int ordnumnew = (from ord in _context.TblOrders
                                 select ord).Count();

                if ((ordnumnew = ordnum) != 1)
                {
                    HttpContext.Session.SetInt32("orderID", ordnum);
                }
                else return RedirectToAction(nameof(Index));
            }

            return View(neworder);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TblOrders == null)
            {
                return NotFound();
            }

            var tblOrder = await _context.TblOrders
                .FirstOrDefaultAsync(m => m.ReportId == id);
            if (tblOrder == null)
            {
                return NotFound();
            }

            return View(tblOrder);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TblOrders == null)
            {
                return Problem("Entity set 'Group08ElectricmtContext.TblOrders'  is null.");
            }
            var tblOrder = await _context.TblOrders.FindAsync(id);
            if (tblOrder != null)
            {
                _context.TblOrders.Remove(tblOrder);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblOrderExists(int id)
        {
          return (_context.TblOrders?.Any(e => e.ReportId == id)).GetValueOrDefault();
        }
    }
}

Cloud/Cloud/Controllers/TruckController.cs
using Cloud.Models;
using Microsoft.AspNetCore.Mvc;

namespace Cloud.Controllers
{
    public class TruckController : Controller
    {
        private readonly Group08ElectricmtContext context;

        public TruckController(Group08ElectricmtContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("email") == null)
            {
                return RedirectToAction("Login", "Company");
            }
            else
            {

                int companyID = Convert.ToInt32(HttpContext.Session.GetInt32("companyID"));

                List<TblTruck> listEmp = context.TblTrucks.Where(tr => tr.Status == 1 && tr.CompId == companyID).Select(tr => tr).ToList();

                return View(listEmp);
            }
        }

        public IActionResult Create()
        {
            TblEmployee emp = new TblEmployee();
            var employees = context.TblEmployees.Where(c => c.CompId == HttpContext.Session.GetInt32("companyID")).ToList();

            return View(employees);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TblTruck newtruck)
        {
            if (ModelState.IsValid)
            {
                int trucknum = (from truck in context.TblEmployees
                              select truck).Count();

                newtruck.TruckId = trucknum + 1;
                newtruck.Status = 1;
                newtruck.CompId = HttpContext.Session.GetInt32("companyID");

                context.Add(newtruck);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(newtruck);
        }

        public IActionResult Delete(int id)
        {
            TblTruck truck = context.TblTrucks.Where(t => t.TruckId == id).SingleOrDefault();
            if (truck == null)
            {
                return NotFound();
            }
            return View(truck);
        }

        [HttpPost]
        public IActionResult Delete(TblTruck truck)
        {
            var v = context.TblTrucks.FirstOrDefault(e => e.TruckId == truck.TruckId);

            if (v == null)
            {
                return NotFound();
            }

            v.Status = 0;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Cloud/Cloud/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Mobile Inventory Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Cloud.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <strong><a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="">MobileInventory</a></strong>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Truck" asp-action="Index">Trucks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Order</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (HttpContextAccessor.HttpContext.Session.GetString("email") == null)
                        {
                            <li class="nav-item align-content-end">
                                <a id="loginButton" class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item align-content-end">
                                <a id="registerButton" class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="SignUp">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item align-content-end">
                                <bold><a class="nav-link text-dark">Welcome, @HttpContextAccessor.HttpContext.Session.GetString("email")!</a><bold />
                            </li>
                            <li class="nav-item align-content-end">
                                <form asp-controller="Company" asp-action="Logout" method="post">
                                    <bold><button type="submit" class="nav-link btn btn-link text-dark" style="padding-top: 0.5rem; border: none; background-color: inherit;">Logout</button><bold/>
                                </form>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Cloud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>